refactored mybadgesfragment in compose
mok-it/mok-app pull request #206
Opened 2024-05-24 21:13 UTC by notAnElephant

2024-05-24 21:21 UTC, notAnElephant commented
smh, majd megoldom a conflictokat a review után

2024-05-25 11:04 UTC, matetamasi requested changes

2024-05-25 11:04 UTC, matetamasi commented on app/src/main/java/mok/it/app/mokapp/fragments/viewmodels/MyBadgesViewModel.kt
> +    val myCategories: LiveData<List<Category>> = myProjects.map { projects ->
Lehetne Flow-val?

2024-05-25 11:04 UTC, matetamasi commented on app/src/main/java/mok/it/app/mokapp/model/User.kt
> +    var projectBadges: MutableMap<String, Int> = HashMap(), //TODO change back to val
miért lett var?

2024-05-25 11:06 UTC, notAnElephant commented on app/src/main/java/mok/it/app/mokapp/fragments/MyBadgesFragment.kt
> +            MyBadgesScreen() //TODO apply mokapp theme in the whole fragment
De, de itt még nem létezik ez a method

2024-05-25 13:26 UTC, closed without merging

2024-05-25 13:26 UTC, notAnElephant commented
Ebben a formájában redundans a funkció